name: Screenshot Workflow

on:
  push:
    branches:
      - main
  #schedule:
  #  - cron: '0 * * * *'  # Run every hour at the top of the hour

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install 

    - name: Call screenshotter
      run: npm start

    - name: screenshotter
      run: bash -c ls /tmp
    #- name: Commit changes
      #run: |
        #git config --global user.email "you@example.com"  # Replace with your email address
        #git config --global user.name "Your Name"  # Replace with your name
        #git add .
        #git commit -m "Update data"  # Replace with your own commit message

    #- name: Push changes
      #uses: ad-m/github-push-action@master
      #with:
        #github_token: ${{ secrets.GITHUB_TOKEN }}
        #branch: main  # Replace with the name of the branch you want to push to

